; PlatformIO Project Configuration File
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev
src_dir = src
include_dir = include

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor & Upload Configuration
monitor_speed = 115200
upload_speed = 921600

; Compiler options
build_flags = 
    -DCORE_DEBUG_LEVEL=1
    -DCONFIG_ARDUHAL_LOG_COLORS=1

; Serial monitor filters
monitor_filters = 
    default
    esp32_exception_decoder
